# Generated by Django 5.2.6 on 2025-09-26 01:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fango', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('banned', 'Banned')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('lang', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_en', models.CharField(max_length=255)),
                ('meaning', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('target_lang_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fango.language')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fango.appuser')),
            ],
            options={
                'unique_together': {('user_id', 'quiz_name')},
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_target', models.CharField(max_length=255)),
                ('example_target_easy', models.TextField()),
                ('example_en_easy', models.TextField()),
                ('example_target_med', models.TextField()),
                ('example_en_med', models.TextField()),
                ('example_target_hard', models.TextField()),
                ('example_en_hard', models.TextField()),
                ('audio_name', models.CharField(max_length=255)),
                ('audio_path', models.CharField(max_length=255)),
                ('target_lang_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fango.language')),
                ('word_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fango.word')),
            ],
            options={
                'unique_together': {('target_lang_id', 'word_id')},
            },
        ),
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_name', models.CharField(max_length=255)),
                ('img_path', models.CharField(max_length=255)),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('translation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fango.translation')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fango.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='QuizWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fango.quiz')),
                ('translation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fango.translation')),
            ],
            options={
                'unique_together': {('quiz_id', 'translation_id')},
            },
        ),
    ]
